### ISSUE TITLE
attributes quoted material to Tom

### ISSUE THREAD

**Issue by alvherre** [uhoh-itsmaciek/regardstomlane#2]
See https://twitter.com/regardstomlane/status/679323256407609344 vs https://www.postgresql.org/message-id/13154.1450798166%40sss.pgh.pa.us

**Comment by uhoh-itsmaciek** [comment]
This should be fixed by 610d497fcb36ad6bd8074ad36a35d06ed67045f3 -- please let me know if you see any more issues. I added a test for this specific case in cc40d124ac018d50fb8c66f54817f706a012cadd but it should work in general.
